# render.yaml

services:
  - type: web
    name: backend
    env: docker
    rootDir: chatapplication-backend
    dockerfilePath: Dockerfile

  - type: web
    name: frontend
    env: docker
    rootDir: chatapplication-frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: VITE_API_URL
        value: "/api"
