# render.yaml

services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./chatapplication-backend/Dockerfile

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./chatapplication-frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: "/api"